version: '3'

services:
  client:
    build: ./client
    ports:
      - "80:3000"
    restart: always

  server:
    build: ./server
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MONGO_URI=mongodb://your-mongo-url
