name: CI_Vite React App

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: my-app

      # - name: Run tests with coverage
      #   run: npm run test -- --coverage
      #   working-directory: my-app

      # - name: Upload Coverage Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-report
      #     path: my-app/coverage/