name: CI Workflow

on:
  push:
    branches:
      - tanu
  pull_request:
    branches:
      - tanu

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: my-app
        run: npm ci

      - name: Build the project
        working-directory: my-app
        run: npm run build
        

      - name: Run tests
        working-directory: my-app
        run: npm test